### ISSUE TITLE
It's not possible to chain animation classes 

### ISSUE THREAD

**Issue by fabiankaegy** [10up/component-animate#11]
In my use case I wanted to chain the `slide-in-up` animation with the `fade-in` animation. 

But in doing so, only the last class sets the `animation` css property.

You can directly use the css animation in your own classes. But caining the classes doesn't work

**Expected behavior**
I would expect to be able to set `fade-in slide-in-up` as the class and have the element slide in and fade in at the same time

**Comment by timwright12** [comment]
This is going to be a documentation update on how to chain animations since we can't do that with just classes unless we create extras like `.slide-up-fade-in` which will probably bloat the library too much.

**Comment by timwright12** [comment]
@fabiankaegy I added some documentation under the usage section for this (third tab): https://baseline.10up.com/component/animate/
