### ISSUE TITLE
Feature: JavaScript API

### ISSUE THREAD

**Issue by timwright12** [10up/component-animate#3]

**Comment by timwright12** [comment]
Modeled after bounce.js to product complex JS-based animations. Animations will be chainable and focused on transforms only at first. API should be similar to https://github.com/tictail/bounce.js/ but we'll need to sync on the naming.

**Comment by timwright12** [comment]
importing animations should be available in bulk, but also one by one (e.g. if you only want rotate)

**Comment by nicholasio** [comment]
Closed in favor of https://github.com/10up/component-library/issues/27
